name: mc_caigs_mobile
publish_to: 'none'
description: >-
  Scaffold for the McCaigs Education AI Suite Flutter application supporting
  StudentlyAI, StudentsAI UK, and StudentsAI US brands.
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.4
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
